# Dependencies
markdown:	redcarpet
highlighter:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		experiantal.xyz
tagline:	'blog'
description:	'Outdoors experiental'
url:		http://www.experiental.xyz

author:
  name:		'Marko E. Takanen'
  url:		

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		https://farm8.staticflickr.com/7494/15707427339_de841e90d4_h.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/mtakanen
    desc:	Follow me on twitter


  - icon:	feed
    url:	http://www.experiental.xyz/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Marko E. Takanen
  url:		http://mtakanen.github.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
